
/**************************************************************
 *	
 *	DamageSfx, 8 bit, 11025Hz,
 *	1 channel, 5035 bytes/channel
 *	Total Size: 1 * 5035 + 4 (header) = 5079 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Al\Documents\CollegeFIles\cs2261\FinalProjectM04_AlabdullahMahiyan\AlabdullahMahiyan_FinalProjectM04\FinalProjectM04\DamageSfx.wav
 *	Time-stamp: Mon Apr 24 10:02:40 2017
 *	
 **************************************************************/

#ifndef __DAMAGESFXH__
#define __DAMAGESFXH__

#define DAMAGESFXFREQ 11025
#define DAMAGESFXLEN 5035

extern const unsigned char DamageSfx[5035];

#endif /* __DAMAGESFXH__ */
