
/**************************************************************
 *	
 *	DestroySfx, 8 bit, 11025Hz,
 *	1 channel, 24236 bytes/channel
 *	Total Size: 1 * 24236 + 4 (header) = 24280 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Al\Documents\CollegeFIles\cs2261\FinalProjectM04_AlabdullahMahiyan\AlabdullahMahiyan_FinalProjectM04\FinalProjectM04\DestroySfx.wav
 *	Time-stamp: Wed Apr 19 19:26:25 2017
 *	
 **************************************************************/

#ifndef __DESTROYSFXH__
#define __DESTROYSFXH__

#define DESTROYSFXFREQ 11025
#define DESTROYSFXLEN 24236

extern const unsigned char DestroySfx[24236];

#endif /* __DESTROYSFXH__ */
