
/**************************************************************
 *	
 *	DoorSfx, 8 bit, 11025Hz,
 *	1 channel, 3925 bytes/channel
 *	Total Size: 1 * 3925 + 4 (header) = 3969 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Al\Documents\CollegeFIles\cs2261\FinalProjectM04_AlabdullahMahiyan\AlabdullahMahiyan_FinalProjectM04\FinalProjectM04\DoorSfx.wav
 *	Time-stamp: Wed Apr 19 19:26:30 2017
 *	
 **************************************************************/

#ifndef __DOORSFXH__
#define __DOORSFXH__

#define DOORSFXFREQ 11025
#define DOORSFXLEN 3925

extern const unsigned char DoorSfx[3925];

#endif /* __DOORSFXH__ */
