
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 453475 bytes/channel
 *	Total Size: 1 * 453475 + 4 (header) = 453519 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Al\Documents\CollegeFIles\cs2261\FinalProjectM04_AlabdullahMahiyan\AlabdullahMahiyan_FinalProjectM04\FinalProjectM04\GameSong.wav
 *	Time-stamp: Mon Apr 24 09:59:56 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 453475

extern const unsigned char GameSong[453475];

#endif /* __GAMESONGH__ */
