
/**************************************************************
 *	
 *	GameOverSong, 8 bit, 11025Hz,
 *	1 channel, 414554 bytes/channel
 *	Total Size: 1 * 414554 + 4 (header) = 414598 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Al\Documents\CollegeFIles\cs2261\FinalProjectM04_AlabdullahMahiyan\AlabdullahMahiyan_FinalProjectM04\FinalProjectM04\GameOverSong.wav
 *	Time-stamp: Mon Apr 24 02:59:25 2017
 *	
 **************************************************************/

#ifndef __GAMEOVERSONGH__
#define __GAMEOVERSONGH__

#define GAMEOVERSONGFREQ 11025
#define GAMEOVERSONGLEN 414554

extern const unsigned char GameOverSong[414554];

#endif /* __GAMEOVERSONGH__ */
