
/**************************************************************
 *	
 *	LaserSfx, 8 bit, 11025Hz,
 *	1 channel, 3007 bytes/channel
 *	Total Size: 1 * 3007 + 4 (header) = 3051 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Al\Documents\CollegeFIles\cs2261\FinalProjectM04_AlabdullahMahiyan\FinalProjectM04\LaserSfx.wav
 *	Time-stamp: Tue Apr 11 16:57:23 2017
 *	
 **************************************************************/

#ifndef __LASERSFXH__
#define __LASERSFXH__

#define LASERSFXFREQ 11025
#define LASERSFXLEN 3007

extern const unsigned char LaserSfx[3007];

#endif /* __LASERSFXH__ */
